"""Unificar enums feriado y defaults

Revision ID: 0178dbe05059
Revises: e60239e5b368
Create Date: 2025-12-19 17:59:47.094083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0178dbe05059'
down_revision = 'e60239e5b368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion_recargos', schema=None) as batch_op:
       batch_op.alter_column('tipo_feriado', existing_type=sa.Enum('NORMAL', 'IRRENUNCIABLE', name='tipo_feriado_recargo'), type_=sa.Enum('NORMAL', 'IRRENUNCIABLE', name='tipo_feriado'),
              existing_nullable=True,
              postgresql_using="tipo_feriado::text::tipo_feriado"
       )

    with op.batch_alter_table('guardias', schema=None) as batch_op:
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('turnos_registro', schema=None) as batch_op:
        batch_op.alter_column('minutos_feriado',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('monto_recargo',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('creado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos_registro', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('monto_recargo',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('minutos_feriado',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('guardias', schema=None) as batch_op:
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('configuracion_recargos', schema=None) as batch_op:
        batch_op.alter_column('tipo_feriado',
               existing_type=sa.Enum('NORMAL', 'IRRENUNCIABLE', name='tipo_feriado'),
               type_=postgresql.ENUM('NORMAL', 'IRRENUNCIABLE', name='tipo_feriado_recargo'),
               nullable=True)

    # ### end Alembic commands ###
