"""Anulacion (soft delete) turnos

Revision ID: 106879fcf0cd
Revises: 8ea4e86d749e
Create Date: 2025-12-19 05:18:56.197187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106879fcf0cd'
down_revision = '8ea4e86d749e'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('turnos_registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anulado', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('anulado_en', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('anulado_motivo', sa.String(length=250), nullable=True))

    # opcional: remover server_default para que quede limpio en schema
    with op.batch_alter_table('turnos_registro', schema=None) as batch_op:
        batch_op.alter_column('anulado', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos_registro', schema=None) as batch_op:
        batch_op.drop_column('anulado_motivo')
        batch_op.drop_column('anulado_en')
        batch_op.drop_column('anulado')

    # ### end Alembic commands ###
