"""Crear tablas iniciales

Revision ID: 526aee9ada93
Revises:
Create Date: 2025-12-19 05:03:59.868498

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "526aee9ada93"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feriados",
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum("NORMAL", "IRRENUNCIABLE", name="tipo_feriado"),
            nullable=False,
        ),
        sa.Column("descripcion", sa.String(length=150), nullable=True),
        sa.PrimaryKeyConstraint("fecha"),
    )
    op.create_table(
        "guardias",
        sa.Column("rut", sa.String(length=12), nullable=False),
        sa.Column("ap_paterno", sa.String(length=50), nullable=False),
        sa.Column("ap_materno", sa.String(length=50), nullable=True),
        sa.Column("nombres", sa.String(length=100), nullable=False),
        sa.Column("cargo", sa.String(length=100), nullable=True),
        sa.Column("empleador", sa.String(length=100), nullable=True),
        sa.Column("obra_base", sa.String(length=100), nullable=True),
        sa.Column(
            "modalidad",
            sa.Enum("JC", "PT", "EXT", name="modalidad_guardia"),
            nullable=False,
        ),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("rut"),
    )
    op.create_table(
        "instalaciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "turnos_registro",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guardia_rut", sa.String(length=12), nullable=False),
        sa.Column("instalacion_id", sa.Integer(), nullable=False),
        sa.Column("inicio_dt", sa.DateTime(), nullable=False),
        sa.Column("fin_dt", sa.DateTime(), nullable=False),
        sa.Column(
            "turno_codigo", sa.Enum("DIA", "NOCHE", name="turno_codigo"), nullable=False
        ),
        sa.Column("observacion", sa.String(length=250), nullable=True),
        sa.Column("minutos_totales", sa.Integer(), nullable=False),
        sa.Column("minutos_feriado", sa.Integer(), nullable=True),
        sa.Column("es_adicional", sa.Boolean(), nullable=False),
        sa.Column("monto_base", sa.Integer(), nullable=False),
        sa.Column("monto_recargo", sa.Integer(), nullable=True),
        sa.Column("monto_total", sa.Integer(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["guardia_rut"],
            ["guardias.rut"],
        ),
        sa.ForeignKeyConstraint(
            ["instalacion_id"],
            ["instalaciones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("turnos_registro")
    op.drop_table("instalaciones")
    op.drop_table("guardias")
    op.drop_table("feriados")
    # ### end Alembic commands ###
