"""Configuracion recargos feriados

Revision ID: 8ea4e86d749e
Revises: 526aee9ada93
Create Date: 2025-12-19 05:10:58.578965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea4e86d749e'
down_revision = '526aee9ada93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_recargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_feriado', sa.Enum('NORMAL', 'IRRENUNCIABLE', name='tipo_feriado_recargo'), nullable=True),
    sa.Column('porcentaje', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_feriado')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracion_recargos')
    # ### end Alembic commands ###
