"""Trazabilidad recargo feriado en turnos

Revision ID: 95a30bcaf67a
Revises: 106879fcf0cd
Create Date: 2025-12-19 14:32:39.540855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a30bcaf67a'
down_revision = '106879fcf0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos_registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feriado_tipo_aplicado', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('feriado_porcentaje_aplicado', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('feriado_descripcion_aplicada', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('feriado_detalle_calculo', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos_registro', schema=None) as batch_op:
        batch_op.drop_column('feriado_detalle_calculo')
        batch_op.drop_column('feriado_descripcion_aplicada')
        batch_op.drop_column('feriado_porcentaje_aplicado')
        batch_op.drop_column('feriado_tipo_aplicado')

    # ### end Alembic commands ###
