"""Comentarios de revision por turno

Revision ID: ea05a69145a0
Revises: 0178dbe05059
Create Date: 2025-12-19 18:51:27.810843

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ea05a69145a0"
down_revision = "0178dbe05059"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "turnos_comentarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("turno_id", sa.Integer(), nullable=False),
        sa.Column("autor_id", sa.Integer(), nullable=False),
        sa.Column("texto", sa.String(length=500), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("resuelto", sa.Boolean(), nullable=False),
        sa.Column("resuelto_en", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["autor_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["turno_id"],
            ["turnos_registro.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("turnos_comentarios", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_turnos_comentarios_autor_id"), ["autor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_turnos_comentarios_turno_id"), ["turno_id"], unique=False
        )

    with op.batch_alter_table("configuracion_recargos", schema=None) as batch_op:
        batch_op.alter_column(
            "tipo_feriado",
            existing_type=postgresql.ENUM(
                "NORMAL", "IRRENUNCIABLE", name="tipo_feriado"
            ),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("configuracion_recargos", schema=None) as batch_op:
        batch_op.alter_column(
            "tipo_feriado",
            existing_type=postgresql.ENUM(
                "NORMAL", "IRRENUNCIABLE", name="tipo_feriado"
            ),
            nullable=True,
        )

    with op.batch_alter_table("turnos_comentarios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_turnos_comentarios_turno_id"))
        batch_op.drop_index(batch_op.f("ix_turnos_comentarios_autor_id"))

    op.drop_table("turnos_comentarios")
    # ### end Alembic commands ###
